module.exports = {
    createAwardee: {
        name: { type: 'string', min: 3, max: 100 },
        photo_id: { type: 'number', integer: true, optional: true },
        birth_date: { type: "string", format: "date" },
        linkedin_username: { type: 'string', min: 3, max: 100 },
        instagram_username: { type: 'string', min: 3, max: 100 },
        telp: { type: 'string', optional: true, pattern: /^[0-9]+$/, min: 10, max: 15},
        member_since: { type: 'string', format: "date", optional: true },
        scholarship: { type: 'number', integer: true, positive:true },
        nim: { type: 'string', min: 6, max: 8, pattern: /^[0-9]+$/ },
        study_program_id: { type: 'number', integer: true },
        year: { type: 'string', min: 4, max: 4, pattern: /^[0-9]+$/ },
        smt1_ip: 'number',
        smt2_ip: 'number',
        smt3_ip: 'number',
        smt4_ip: { type: 'number', optional: true, nullable: true },
        smt5_ip: { type: 'number', optional: true, nullable: true },
        smt6_ip: { type: 'number', optional: true, nullable: true },
        smt7_ip: { type: 'number', optional: true, nullable: true },
        smt8_ip: { type: 'number', optional: true, nullable: true },
        smt1_ipk: 'number',
        smt2_ipk: 'number',
        smt3_ipk: 'number',
        smt4_ipk: { type: 'number', optional: true, nullable: true },
        smt5_ipk: { type: 'number', optional: true, nullable: true },
        smt6_ipk: { type: 'number', optional: true, nullable: true },
        smt7_ipk: { type: 'number', optional: true, nullable: true },
        smt8_ipk: { type: 'number', optional: true, nullable: true },
        transcript_id: { type: 'number', optional: true, nullable: true },
    },
    updateAwardee: {
        name: { type: 'string', min: 3, max: 100, optional: true },
        photo_id: { type: 'number', integer: true, optional: true },
        birth_date: { type: "string", format: "date", optional: true },
        linkedin_username: { type: 'string', min: 3, max: 100, optional: true },
        instagram_username: { type: 'string', min: 3, max: 100, optional: true },
        telp: { type: 'string', optional: true, pattern: /^[0-9]+$/, min: 10, max: 15},
        member_since: { type: 'string', format: "date", optional: true },
        scholarship: { type: 'number', integer: true, positive:true, optional: true },
        nim: { type: 'string', min: 6, max: 8, pattern: /^[0-9]+$/, optional: true },
        study_program_id: { type: 'number', integer: true, optional: true },
        year: { type: 'string', min: 4, max: 4, pattern: /^[0-9]+$/, optional: true },
        smt1_ip: { type: 'number', optional: true },
        smt2_ip: { type: 'number', optional: true },
        smt3_ip: { type: 'number', optional: true },
        smt4_ip: { type: 'number', optional: true, nullable: true },
        smt5_ip: { type: 'number', optional: true, nullable: true },
        smt6_ip: { type: 'number', optional: true, nullable: true },
        smt7_ip: { type: 'number', optional: true, nullable: true },
        smt8_ip: { type: 'number', optional: true, nullable: true },
        smt1_ipk: { type: 'number', optional: true },
        smt2_ipk: { type: 'number', optional: true },
        smt3_ipk: { type: 'number', optional: true },
        smt4_ipk: { type: 'number', optional: true, nullable: true },
        smt5_ipk: { type: 'number', optional: true, nullable: true },
        smt6_ipk: { type: 'number', optional: true, nullable: true },
        smt7_ipk: { type: 'number', optional: true, nullable: true },
        smt8_ipk: { type: 'number', optional: true, nullable: true },
        transcript_id: { type: 'number', optional: true, nullable: true },
    },
};