'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
   await queryInterface.bulkInsert('awardee', [
    {
      user_id: 1,
      name: "Ilham Fachry Ramdhan",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-11-21",
      linkedin_username: "",
      instagram_username: "ilhamfachryr",
      telp: "",
      member_since: null,
      department_id: 1,
      division_id: 1,
      position_id: 1,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 2,
      name: "Zulfa Haura",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-04-07",
      linkedin_username: "",
      instagram_username: "zulfahaura",
      telp: "",
      member_since: null,
      department_id: 1,
      division_id: 1,
      position_id: 1,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 3,
      name: "Wilda Riva Fadhilah",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-01-25",
      linkedin_username: "",
      instagram_username: "wildariva",
      telp: "",
      member_since: null,
      department_id: 1,
      division_id: 1,
      position_id: 1,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 4,
      name: "Eka Tiara Nur Fitriana",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-11-28",
      linkedin_username: "ekatiaranurf",
      instagram_username: "ekatiaranurf",
      telp: "089677920951",
      member_since: "2023-01-01",
      department_id: 2,
      division_id: null,
      position_id: 4,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2058491",
      study_program_id: 44,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 5,
      name: "Shafa Salsabila",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-08-19",
      linkedin_username: null,
      instagram_username: "shafasb__",
      telp: "08888291197",
      member_since: "2022-01-01",
      department_id: 2,
      division_id: 4,
      position_id: 5,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2095728",
      study_program_id: 44,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 6,
      name: "Muhammad Azar Nuzy",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-11-06",
      linkedin_username: null,
      instagram_username: "azar_nuzy",
      telp: "082246449106",
      member_since: "2022-01-01",
      department_id: 2,
      division_id: 4,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2004191",
      study_program_id: 49,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 7,
      name: "Sekar Madu Kusumawardani",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-07-03",
      linkedin_username: "sekarmk03",
      instagram_username: "sekarmk03",
      telp: "089691798633",
      member_since: "2022-01-01",
      department_id: 2,
      division_id: 4,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2007703",
      study_program_id: 49,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 8,
      name: "Azaki Shaleh Albany",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-08-03",
      linkedin_username: "azakialbany",
      instagram_username: "azakialbany",
      telp: "089691798633",
      member_since: "2022-01-01",
      department_id: 2,
      division_id: 4,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2079856",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 9,
      name: "Neysa Ardhina",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-02-21",
      linkedin_username: null,
      instagram_username: "neysaardhina",
      telp: "082117842951",
      member_since: "2022-01-01",
      department_id: 2,
      division_id: 4,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2023571",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 10,
      name: "Denis Erlangga Maulana",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-10-01",
      linkedin_username: null,
      instagram_username: "denismaulanaa_",
      telp: "082123333789",
      member_since: "2022-01-01",
      department_id: 2,
      division_id: 4,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2064329",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 11,
      name: "Nadira Arevia Hermawan",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-10-27",
      linkedin_username: "nadiraarevia",
      instagram_username: "nadiraarevia",
      telp: "082297392245",
      member_since: "2022-01-01",
      department_id: 2,
      division_id: 4,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2087152",
      study_program_id: 44,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 12,
      name: "Mochammad Diponegoro",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-09-27",
      linkedin_username: "dipoalm",
      instagram_username: "dipoalm",
      telp: "089524930050",
      member_since: "2023-01-01",
      department_id: 2,
      division_id: 5,
      position_id: 5,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2089347",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 13,
      name: "Davu Raissa Elazar",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-05-10",
      linkedin_username: null,
      instagram_username: "davu.elazar",
      telp: "081223456934",
      member_since: "2023-01-01",
      department_id: 2,
      division_id: 5,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2148963",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2021",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 14,
      name: "Dwi Novia Al Husaeni",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2000-12-04",
      linkedin_username: "dwi-novia-al-husaeni-855725243",
      instagram_username: "dwin0_0viaa",
      telp: "082315516625",
      member_since: "2023-01-01",
      department_id: 2,
      division_id: 5,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2153746",
      study_program_id: 44,
      year: "2021",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 15,
      name: "Tsalsabilla Nurfitriyatna Putri",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-12-12",
      linkedin_username: "tsalsabillanf",
      instagram_username: "tsalsabillanf",
      telp: "081322565213",
      member_since: "2023-01-01",
      department_id: 2,
      division_id: 5,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2032459",
      study_program_id: 44,
      year: "2020",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt4_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt5_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt6_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt7_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt8_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      transcript_id: Math.floor(Math.random() * 2) + 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 16,
      name: "Raden Wahyuni Qoyyumiah",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-01-19",
      linkedin_username: "",
      instagram_username: "qoyyum19",
      telp: "",
      member_since: null,
      department_id: 3,
      division_id: null,
      position_id: 4,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 17,
      name: "Afina Faza ",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-09-29",
      linkedin_username: "",
      instagram_username: "afinaafz",
      telp: "",
      member_since: null,
      department_id: 3,
      division_id: 6,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 18,
      name: "Najwa Rahmadina",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-11-04",
      linkedin_username: "",
      instagram_username: "najwa.rhmdn4",
      telp: "",
      member_since: null,
      department_id: 3,
      division_id: 6,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 19,
      name: "Eptina Fatmawati",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-12-25",
      linkedin_username: "",
      instagram_username: "@ftiina_",
      telp: "",
      member_since: null,
      department_id: 3,
      division_id: 7,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 20,
      name: "Arif Daffi Zaini A'lauddin ",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-06-23",
      linkedin_username: "",
      instagram_username: "arfdaffi",
      telp: "",
      member_since: null,
      department_id: 3,
      division_id: 7,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 21,
      name: "Rida Nursiami",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-11-15",
      linkedin_username: "",
      instagram_username: "rid.aanr",
      telp: "",
      member_since: null,
      department_id: 3,
      division_id: 7,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 22,
      name: "Harry Ramadhani Hakim",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-11-29",
      linkedin_username: "",
      instagram_username: "harryerha_",
      telp: "",
      member_since: null,
      department_id: 3,
      division_id: 7,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 23,
      name: "Karina Salsa Sabila",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-03-02",
      linkedin_username: "",
      instagram_username: "karinasalsasabilaa",
      telp: "",
      member_since: null,
      department_id: 4,
      division_id: null,
      position_id: 4,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 24,
      name: "Irham Jundurahmaan",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-10-10",
      linkedin_username: "",
      instagram_username: "",
      telp: "",
      member_since: null,
      department_id: 4,
      division_id: 8,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 25,
      name: "Neng Sofa Mawadatan Nasriyah",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-07-01",
      linkedin_username: "",
      instagram_username: "sofawwmwadtan",
      telp: "",
      member_since: null,
      department_id: 4,
      division_id: 8,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 26,
      name: "Lulub Nurkhaliza ",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2004-07-16",
      linkedin_username: "",
      instagram_username: "lulubnrkhlz",
      telp: "",
      member_since: null,
      department_id: 4,
      division_id: 8,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 27,
      name: "Muhammad Rifqi Putra Yudisha ",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-08-25",
      linkedin_username: "",
      instagram_username: "rifqiiputraa",
      telp: "",
      member_since: null,
      department_id: 4,
      division_id: 8,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 28,
      name: "Raihan Syeka Pramukastie",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-11-28",
      linkedin_username: "",
      instagram_username: "rehanseekap",
      telp: "",
      member_since: null,
      department_id: 4,
      division_id: 9,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 29,
      name: "Sajida I'tikafah Laila",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-08-19",
      linkedin_username: "",
      instagram_username: "sajidaitikafah_03",
      telp: "",
      member_since: null,
      department_id: 4,
      division_id: 9,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 30,
      name: "Nasya Retnadella",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-05-26",
      linkedin_username: "",
      instagram_username: "nasyaretna",
      telp: "",
      member_since: null,
      department_id: 4,
      division_id: 9,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 31,
      name: "Gesika Putri Kencana Arum",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2004-02-12",
      linkedin_username: "",
      instagram_username: "geeessssssssss",
      telp: "",
      member_since: null,
      department_id: 4,
      division_id: 9,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 32,
      name: "Meiliani Maulidia Putri",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-05-05",
      linkedin_username: "",
      instagram_username: "grizzlymayy",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: null,
      position_id: 4,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 33,
      name: "Selya Arifa Nurfitri",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-11-26",
      linkedin_username: "",
      instagram_username: "selyaarifa",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 10,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 34,
      name: "Syifa Shofadianti R",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-07-11",
      linkedin_username: "",
      instagram_username: "ssyifaas",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 10,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 35,
      name: "Lianna Rizky Gunawan",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-06-06",
      linkedin_username: "",
      instagram_username: "lianna_na66",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 10,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 36,
      name: "Nadzira Azzahra",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-07-23",
      linkedin_username: "",
      instagram_username: "nadzira_23",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 10,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 37,
      name: "Fitri Handayani",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-12-14",
      linkedin_username: "",
      instagram_username: "pitlefit",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 11,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 38,
      name: "Aqlan Kamal Alfarizi",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-09-03",
      linkedin_username: "",
      instagram_username: "aqlnalf",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 11,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 39,
      name: "Fathima Nuri Azizah Irsyad",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-09-26",
      linkedin_username: "",
      instagram_username: "uni_fathima",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 11,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 40,
      name: "Yasmine Azzahra",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2004-01-02",
      linkedin_username: "",
      instagram_username: "ysmnazzhr",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 11,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 41,
      name: "Abdullah Habsyi",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-04-16",
      linkedin_username: "",
      instagram_username: "abdullahhabsyi_",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 11,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 42,
      name: "Azzam Dzubyan Syahidan ",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2004-06-17",
      linkedin_username: "",
      instagram_username: "dzubyaan_",
      telp: "",
      member_since: null,
      department_id: 5,
      division_id: 11,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 43,
      name: "Laudy Noval Permana",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2004-01-19",
      linkedin_username: "",
      instagram_username: "laudynoval",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: null,
      position_id: 4,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 44,
      name: "Muhammad Rafi Akbar",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-02-11",
      linkedin_username: "",
      instagram_username: "",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 12,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 45,
      name: "Ratna Wulan Dari",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-06-25",
      linkedin_username: "",
      instagram_username: "ratnaaawlndr",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 12,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 46,
      name: "Muhammad Aqsa Novaldi",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2000-11-25",
      linkedin_username: "",
      instagram_username: "aqsanovaldii",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 12,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 47,
      name: "Muhammad Fikri Yunus Musabik Firdaus",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-11-24",
      linkedin_username: "",
      instagram_username: "musabikfikri",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 12,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 48,
      name: "Khaila Neisyandiva Nurraendra",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-11-26",
      linkedin_username: "",
      instagram_username: "khail.aa",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 12,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 49,
      name: "Lola Rahayu",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-08-12",
      linkedin_username: "",
      instagram_username: "hararhy_",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 12,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 50,
      name: "Muhammad Akmaluddin Andayani Komara",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-10-13",
      linkedin_username: "",
      instagram_username: "akmaludang",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 12,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 51,
      name: "Fania Hafidza Dwitarachmi",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-07-17",
      linkedin_username: "",
      instagram_username: "faniahafidza",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 13,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 52,
      name: "Ayunda Faza Yuditia",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-07-22",
      linkedin_username: "",
      instagram_username: "ayundafy",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 13,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 53,
      name: "Rafi Arsalan Mi'raj",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-09-24",
      linkedin_username: "",
      instagram_username: "raparsalan",
      telp: "",
      member_since: null,
      department_id: 6,
      division_id: 13,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 54,
      name: "Anisa Nurhalimah",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-02-11",
      linkedin_username: "",
      instagram_username: "a.hlmh",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: null,
      position_id: 4,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 55,
      name: "Rindiawati",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-02-04",
      linkedin_username: "",
      instagram_username: "rndia_",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: 14,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 56,
      name: "Aura Putri Fadlillah ",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-08-12",
      linkedin_username: "",
      instagram_username: "arauraap",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: 14,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 57,
      name: "Dewi Anggraeni",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2005-08-25",
      linkedin_username: "",
      instagram_username: "dewiangrni_",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: 14,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 58,
      name: "Anis Baikunia ",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-10-03",
      linkedin_username: "",
      instagram_username: "anis_5.b",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: 14,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 59,
      name: "Syifa Khairunnisa",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2004-04-24",
      linkedin_username: "",
      instagram_username: "syifakhairunnisa24",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: 14,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 60,
      name: "Ibrahim Danial Bisulthon",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-08-25",
      linkedin_username: "",
      instagram_username: "ibrahimdanial_",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: 15,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 61,
      name: "Gita Tania Oktaviani",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-10-09",
      linkedin_username: "",
      instagram_username: "gitania910",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: 15,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 62,
      name: "Elsa Nurmadhani",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-11-16",
      linkedin_username: "",
      instagram_username: "elsa_nrd09",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: 15,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 63,
      name: "Santika Millenia Ekaparman",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2000-01-06",
      linkedin_username: "",
      instagram_username: "santika.sun23",
      telp: "",
      member_since: null,
      department_id: 7,
      division_id: 15,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 64,
      name: "Ridwan Maulana",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-08-29",
      linkedin_username: "",
      instagram_username: "ridwnmaul_",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: null,
      position_id: 4,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 65,
      name: "Tiyo Saputra",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-01-27",
      linkedin_username: "",
      instagram_username: "tiyosaputraa",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 16,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 66,
      name: "Fadjrin Diraja Muhammad",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-09-14",
      linkedin_username: "",
      instagram_username: "fadjrindirajaa",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 16,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 67,
      name: "Dzulfikri Najmul Falah",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2004-09-25",
      linkedin_username: "",
      instagram_username: "dzulfikrinf",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 16,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 68,
      name: "Hasna Rania Salsabila",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-12-25",
      linkedin_username: "",
      instagram_username: "hasnaranias",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 16,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 69,
      name: "Aida Rochmana Putri",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-07-12",
      linkedin_username: "",
      instagram_username: "aidaaptr",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 16,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 70,
      name: "Dini Kulsum",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-03-06",
      linkedin_username: "",
      instagram_username: "dinikulsum06",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 16,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 71,
      name: "Muhamad Bayu Pramesta",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-02-03",
      linkedin_username: "",
      instagram_username: "bayupramesta_",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 17,
      position_id: 5,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 72,
      name: "Chika Almalia Agisti",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-08-15",
      linkedin_username: "",
      instagram_username: "chikaagisti",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 17,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 73,
      name: "Debi Nabtalia ",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2003-03-21",
      linkedin_username: "",
      instagram_username: "debiliaa",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 17,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 74,
      name: "Nonisa Rodiyana Dwi Putri",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2001-01-01",
      linkedin_username: "",
      instagram_username: "nonisardp",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 17,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      user_id: 75,
      name: "Linda Roman Habeahan",
      photo_id: Math.floor(Math.random() * 4) + 1,
      birth_date: "2002-12-08",
      linkedin_username: "",
      instagram_username: "lindaromanhabeahan",
      telp: "",
      member_since: null,
      department_id: 8,
      division_id: 17,
      position_id: 6,
      scholarship: 0,
      nim: "",
      study_program_id: null,
      year: "",
      smt1_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ip: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ip: null,
      smt4_ip: null,
      smt5_ip: null,
      smt6_ip: null,
      smt7_ip: null,
      smt8_ip: null,
      smt1_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt2_ipk: 3 + parseFloat(Math.random().toFixed(2)),
      smt3_ipk: null,
      smt4_ipk: null,
      smt5_ipk: null,
      smt6_ipk: null,
      smt7_ipk: null,
      smt8_ipk: null,
      transcript_id: null,
      created_at: new Date(),
      updated_at: new Date()
    },
   ], {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('awardee', null, {});
  }
};
