'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
    */
   await queryInterface.bulkInsert('awardee', [
    {
      uuid: "78ae90af-cfc9-4a7b-ba32-0fc7f593e40a",
      name: "Eka Tiara Nur Fitriana",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2001-11-28",
      linkedin_username: "ekatiaranurf",
      instagram_username: "ekatiaranurf",
      telp: "089677920951",
      member_since: "2023-01-01",
      division_id: 1,
      position_id: 4,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2058491",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "51b972b0-609c-4a8a-a74b-2e662ef4efc8",
      name: "Shafa Salsabila",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2002-08-19",
      linkedin_username: null,
      instagram_username: "shafasb__",
      telp: "08888291197",
      member_since: "2022-01-01",
      division_id: 1,
      position_id: 5,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2095728",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "e4c3358b-846c-42b0-b4b5-97a61f13cefb",
      name: "Muhammad Azar Nuzy",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2001-11-06",
      linkedin_username: null,
      instagram_username: "azar_nuzy",
      telp: "082246449106",
      member_since: "2022-01-01",
      division_id: 1,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2004191",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "d98a7247-8137-4a01-82f0-950e2bb4fe3e",
      name: "Sekar Madu Kusumawardani",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2002-07-03",
      linkedin_username: "sekarmk03",
      instagram_username: "sekarmk03",
      telp: "089691798633",
      member_since: "2022-01-01",
      division_id: 1,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2007703",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "0f34e63f-c25b-4c4a-8a0d-89c704e340db",
      name: "Azaki Shaleh Albany",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2002-08-03",
      linkedin_username: "azakialbany",
      instagram_username: "azakialbany",
      telp: "089691798633",
      member_since: "2022-01-01",
      division_id: 1,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2079856",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "a7c69f5a-d19e-492a-8e5d-15e36d3ec39a",
      name: "Neysa Ardhina",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2002-02-21",
      linkedin_username: null,
      instagram_username: "neysaardhina",
      telp: "082117842951",
      member_since: "2022-01-01",
      division_id: 1,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2023571",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "31e523f8-891b-48d3-9f4e-7007eeb6c7eb",
      name: "Denis Erlangga Maulana",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2001-10-01",
      linkedin_username: null,
      instagram_username: "denismaulanaa_",
      telp: "082123333789",
      member_since: "2022-01-01",
      division_id: 1,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2064329",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "f9cc33cd-9c0d-4cbf-af3a-6a53c3f0de7d",
      name: "Nadira Arevia Hermawan",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2002-10-27",
      linkedin_username: "nadiraarevia",
      instagram_username: "nadiraarevia",
      telp: "082297392245",
      member_since: "2022-01-01",
      division_id: 1,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2087152",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "7bfcc72b-ff7d-4eaa-b79c-7a42d2a99c1d",
      name: "Mochammad Diponegoro",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2001-09-27",
      linkedin_username: "dipoalm",
      instagram_username: "dipoalm",
      telp: "089524930050",
      member_since: "2023-01-01",
      division_id: 1,
      position_id: 5,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2089347",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "c67d4a15-b1f5-4e94-9a5e-17739a509b8b",
      name: "Davu Raissa Elazar",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2003-05-10",
      linkedin_username: null,
      instagram_username: "davu.elazar",
      telp: "081223456934",
      member_since: "2023-01-01",
      division_id: 1,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2148963",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2021",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "e10b1ea1-11f5-4959-9e1b-2c74c4a0d447",
      name: "Dwi Novia Al Husaeni",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2000-12-04",
      linkedin_username: "dwi-novia-al-husaeni-855725243",
      instagram_username: "dwin0_0viaa",
      telp: "082315516625",
      member_since: "2023-01-01",
      division_id: 1,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2153746",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2021",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
    {
      uuid: "24d71915-6313-430c-bc37-85db5c662a9b",
      name: "Tsalsabilla Nurfitriyatna Putri",
      photo_id: Math.floor(Math.random() * 2) + 1,
      birth_date: "2001-12-12",
      linkedin_username: "tsalsabillanf",
      instagram_username: "tsalsabillanf",
      telp: "081322565213",
      member_since: "2023-01-01",
      division_id: 1,
      position_id: 6,
      scholarship: Math.floor(Math.random() * 4) + 1,
      nim: "2032459",
      study_program_id: Math.floor(Math.random() * 10) + 1,
      year: "2020",
      smt1_ip: 3 + Math.random().toFixed(2),
      smt2_ip: 3 + Math.random().toFixed(2),
      smt3_ip: 3 + Math.random().toFixed(2),
      smt4_ip: 3 + Math.random().toFixed(2),
      smt5_ip: 3 + Math.random().toFixed(2),
      smt6_ip: 3 + Math.random().toFixed(2),
      smt7_ip: 3 + Math.random().toFixed(2),
      smt8_ip: 3 + Math.random().toFixed(2),
      smt1_ipk: 3 + Math.random().toFixed(2),
      smt2_ipk: 3 + Math.random().toFixed(2),
      smt3_ipk: 3 + Math.random().toFixed(2),
      smt4_ipk: 3 + Math.random().toFixed(2),
      smt5_ipk: 3 + Math.random().toFixed(2),
      smt6_ipk: 3 + Math.random().toFixed(2),
      smt7_ipk: 3 + Math.random().toFixed(2),
      smt8_ipk: 3 + Math.random().toFixed(2),
      transcript_id: 1,
      created_at: new Date(),
      updated_at: new Date()
    },
   ], {});
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
